env:
  browser: true
  # es2021: true
extends:
  - standard
  - prettier # gets the chance to override other
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-undef: off
  no-unused-vars: off
  # "@typescript-eslint/no-unused-vars":
  #   - error
globals:
  $: true
  $$: true
  browser: true
