version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.0-20211123
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    ports:
      - 5900:5900
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20211123
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4

  selenium-hub:
    image: selenium/hub:4.1.0-20211123
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
